src/main/java/com/faforever/api/achievements/AchievementDefinitionRepository.java
src/main/java/com/faforever/api/achievements/PlayerAchievementRepository.java
src/main/java/com/faforever/api/client/OAuthClientRepository.java
src/main/java/com/faforever/api/i18n/MessageRepository.java
src/main/java/com/faforever/api/user/UserRepository.java

#	src/main/java/com/faforever/api/clan/ClanRepository.java
#	src/main/java/com/faforever/api/player/PlayerRepository.java

Add @Repository

---

src/main/java/com/faforever/api/data/domain/Login.java
src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java
src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java
src/test/java/com/faforever/integration/TestDatabase.java
src/test/java/com/faforever/integration/factories/PlayerFactory.java
src/test/java/com/faforever/integration/factories/SessionFactory.java
src/test/java/com/faforever/integration/utils/MockMvcHelper.java
src/test/resources/config/application.yml

[HIGH PRIORITY] Fix Integration Tests

---

src/main/java/com/faforever/api/clan/ClanService.java
src/main/java/com/faforever/api/clan/ClansController.java
src/main/java/com/faforever/api/clan/result/ClanResult.java
src/main/java/com/faforever/api/clan/result/InvitationResult.java
src/main/java/com/faforever/api/clan/result/PlayerResult.java
src/main/java/com/faforever/api/security/JwtService.java
src/test/java/com/faforever/api/clan/ClanServiceTest.java

Fix #66 Don't manually read JSON values, deserialize into a Java object

Fix #66 Don't manually read JSON values, deserialize into a Java object

---

src/main/java/com/faforever/api/clan/result/ClanResult.java
src/main/java/com/faforever/api/data/domain/AbstractEntity.java
src/main/java/com/faforever/api/data/domain/Avatar.java
src/main/java/com/faforever/api/data/domain/Clan.java
src/main/java/com/faforever/api/data/domain/ClanMembership.java
src/main/java/com/faforever/api/data/domain/MapVersion.java
src/main/java/com/faforever/api/data/domain/PlayerAchievement.java
src/main/java/com/faforever/api/data/domain/PlayerEvent.java
src/test/java/com/faforever/api/clan/ClanServiceTest.java
src/test/java/com/faforever/api/data/listeners/ClanEnricherListenerTest.java
src/test/java/com/faforever/integration/factories/ClanFactory.java

https://github.com/FAForever/faf-java-api/pull/74

[HIGH PRIORITY] abstract entitiy class

---

src/main/java/com/faforever/api/config/elide/ElideSwaggerController.java

Fixes #86 Swagger UI produces wrong URLs

Added URL path prefix for data entities to swagger document.

---

src/main/java/com/faforever/api/deployment/LegacyFeaturedModDeploymentTask.java
src/test/java/com/faforever/api/deployment/LegacyFeaturedModDeploymentTaskTest.java

Reverts FAForever/faf-java-api#92

Revert "Use client extension for mod package files"

---

src/main/java/com/faforever/api/ban/BanRepository.java
src/main/java/com/faforever/api/ban/BanService.java
src/main/java/com/faforever/api/config/elide/ElideConfig.java
src/main/java/com/faforever/api/data/checks/permission/BasePermission.java
src/main/java/com/faforever/api/data/checks/permission/HasBanRead.java
src/main/java/com/faforever/api/data/checks/permission/HasBanUpdate.java
src/main/java/com/faforever/api/data/domain/AbstractEntity.java
src/main/java/com/faforever/api/data/domain/BanDurationType.java
src/main/java/com/faforever/api/data/domain/BanInfo.java
src/main/java/com/faforever/api/data/domain/BanLevel.java
src/main/java/com/faforever/api/data/domain/BanRevokeData.java
src/main/java/com/faforever/api/data/domain/BanStatus.java
src/main/java/com/faforever/api/data/domain/Login.java
src/main/java/com/faforever/api/player/PlayerRepository.java
src/main/java/com/faforever/api/security/FafUserDetails.java
src/main/java/com/faforever/api/security/OAuthClientDetails.java
src/test/java/com/faforever/api/data/JsonApiBanIntegrationTest.java
src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java
src/test/java/com/faforever/integration/TestDatabase.java
src/test/java/com/faforever/integration/factories/BanFactory.java

DB Model PR https://github.com/FAForever/db/pull/77
PS.: Codaxy is wrong, method is used. Coveralls is correct, but without Permision System I cannot write any tests ...

[3] Ban Entitites

---

src/main/java/com/faforever/api/achievements/AchievementsController.java
src/main/java/com/faforever/api/config/MvcConfig.java
src/main/java/com/faforever/api/security/OAuthController.java
src/main/java/com/faforever/api/security/OAuthScope.java
src/main/resources/templates/oauth_confirm_access.html

Based on https://github.com/FAForever/faf-java-api/pull/59
only beautify the current login page

[2] Beautify Oauth Approval Page

---

src/main/java/com/faforever/api/avatar/AvatarAssignmentRepository.java
src/main/java/com/faforever/api/avatar/AvatarRepository.java
src/main/java/com/faforever/api/data/domain/Avatar.java
src/main/java/com/faforever/api/data/domain/AvatarAssignment.java
src/main/java/com/faforever/api/data/domain/Player.java
src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java
src/test/java/com/faforever/api/data/JsonApiAvatarIntegrationTest.java
src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java
src/test/java/com/faforever/integration/TestDatabase.java
src/test/java/com/faforever/integration/factories/AvatarFactory.java
src/test/java/com/faforever/integration/factories/BanFactory.java
src/test/java/com/faforever/integration/factories/PlayerFactory.java
src/test/java/com/faforever/integration/factories/SessionFactory.java

DB PR https://github.com/FAForever/db/pull/78

[4] Avatar Entities

---

src/main/java/com/faforever/api/data/domain/Login.java

HotFix #103 Infinite recursion (StackOverflowError)

HotFix #103 Infinite recursion (StackOverflowError)

---

src/main/resources/config/application.yml

https://github.com/FAForever/faf-java-api/issues/118

Clan Invitation default duration is now 7 days

---

src/main/java/com/faforever/api/security/FafUserDetailsService.java

Added the conditional including throwing the relevant exception.
Unless there is anything else that needs to be done, please merge :)

Properly handle "user not found" #112

---

src/main/java/com/faforever/api/data/domain/Division.java
src/main/java/com/faforever/api/data/domain/PlayerDivisionInfo.java

- Do we want to add a `List<PlayerDivisionInfo>` to the `Player`?
- Or maybe do we want to show the current `PlayerDivisionInfo` only? (That would require storing the current season somewhere.)

[RFC] Provide division scores (fixes #135)

---

src/main/java/com/faforever/api/config/elide/ElideConfig.java
src/main/java/com/faforever/api/data/checks/permission/HasLadder1v1Update.java
src/main/java/com/faforever/api/data/domain/Ladder1v1Map.java
src/main/java/com/faforever/api/data/domain/MapVersion.java

Will fix #53
Currently waiting for #46 and https://github.com/FAForever/db/pull/76

Manageable ladder map pool

---

src/main/java/com/faforever/api/data/domain/NameRecord.java
src/main/java/com/faforever/api/data/domain/Player.java
src/main/java/com/faforever/api/db/SchemaVersionVerifier.java
src/main/java/com/faforever/api/name/NameRepository.java
src/test/java/com/faforever/api/data/JsonApiNameIntegrationTest.java
src/test/java/com/faforever/integration/TestDatabase.java
src/test/java/com/faforever/integration/factories/NameRecordFactory.java

[Added by Brutus5000:] Depending on FAForever/db#137
PS.: codacy is wrong, method is used over lombok builder ...

[5] Name Entitiy

---

src/inttest/resources/config/application.yml
src/main/java/com/faforever/api/config/FafApiProperties.java
src/main/java/com/faforever/api/email/EmailService.java
src/main/resources/config/application-dev.yml
src/main/resources/config/application-prod.yml
src/main/resources/config/application.yml
src/test/java/com/faforever/api/email/EmailServiceTest.java

also fixes some missing yml-configs

fixes #162 global email from address and name

---

src/main/java/com/faforever/api/featuredmods/FeaturedModFile.java
src/main/java/com/faforever/api/featuredmods/FeaturedModFileEnricher.java
src/main/java/com/faforever/api/featuredmods/LegacyFeaturedModFileRepository.java

Fix featured mod file URL

---

src/inttest/resources/config/application.yml
src/main/java/com/faforever/api/config/FafApiProperties.java
src/main/java/com/faforever/api/config/security/oauth2/JsonApiOAuthMessageConverter.java
src/main/java/com/faforever/api/config/security/oauth2/JsonApiOauthExceptionRenderer.java
src/main/java/com/faforever/api/mautic/MauticApiErrorHandler.java
src/main/java/com/faforever/api/mautic/MauticApiException.java
src/main/java/com/faforever/api/mautic/MauticErrorResponse.java
src/main/java/com/faforever/api/mautic/MauticService.java
src/main/java/com/faforever/api/user/UserController.java
src/main/java/com/faforever/api/user/UserService.java
src/main/java/com/faforever/api/utils/RemoteAddressUtil.java
src/main/resources/config/application-dev.yml
src/main/resources/config/application-prod.yml
src/test/java/com/faforever/api/mautic/MauticServiceTest.java
src/test/java/com/faforever/api/user/UserServiceTest.java

Create/update Mautic contacts

---

src/inttest/java/com/faforever/api/user/UsersControllerTest.java
src/inttest/resources/config/application.yml
src/main/java/com/faforever/api/config/FafApiProperties.java
src/main/java/com/faforever/api/user/UserService.java
src/main/java/com/faforever/api/user/UsersController.java
src/main/resources/config/application-dev.yml
src/main/resources/config/application-prod.yml
src/test/java/com/faforever/api/user/UserServiceTest.java

It now accepts a callbackUrl that will be called either with a JSON of
errors (in case of failure) or without (in case of success).

Improve how "link to steam" works

---

src/inttest/java/com/faforever/api/data/MapVersionElideTest.java
src/inttest/resources/sql/cleanMapVersion.sql
src/inttest/resources/sql/prepMapVersion.sql
src/main/java/com/faforever/api/config/elide/ElideConfig.java
src/main/java/com/faforever/api/data/checks/BooleanChange.java
src/main/java/com/faforever/api/data/checks/IsEntityOwner.java
src/main/java/com/faforever/api/data/domain/MapVersion.java

Hide map by author

---

src/main/java/com/faforever/api/config/FafApiProperties.java
src/main/java/com/faforever/api/rating/GlobalRatingRepository.java
src/main/java/com/faforever/api/rating/Ladder1v1RatingRepository.java
src/main/java/com/faforever/api/user/UserService.java
src/main/resources/config/application.yml
src/test/java/com/faforever/api/user/UserServiceTest.java

Create rating entries on user account activation

---

src/inttest/java/com/faforever/api/login/LoginTest.java

Closes #238 OAuth tests

---

.travis.yml
src/main/java/com/faforever/api/data/domain/Login.java
src/main/java/com/faforever/api/user/UserService.java
src/main/resources/config/application.yml
src/test/java/com/faforever/api/user/UserServiceTest.java

(Fixes #181)
Depends on db migration v59!

Add last login date to user, set ip address on account activation
